export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const PLUS_NEW_USERS = "PLUS_NEW_USERS";
export const GET_STATUS_NOT_FOUND = "GET_STATUS_NOT_FOUND";


//form

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_CHANGE_PHOTO = "HANDLE_CHANGE_PHOTO";
export const HANDLE_CHANGE_POSITION = "HANDLE_CHANGE_POSITION";


export const FETCH_POSITIONS_START = "FETCH_POSITIONS_START";
export const FETCH_POSITIONS_SUCCESS = "FETCH_POSITIONS_SUCCESS";
export const FETCH_POSITIONS_FALSE = "FETCH_POSITIONS_FALSE";


export const NEW_USER_IS_ADDED = "NEW_USER_IS_ADDED";
export const NEW_USER_IS_ADDED_WITH_ERROR = "NEW_USER_IS_ADDED_WITH_ERROR";

